// Shared stays data for Trip2Trip
window.STAYS = [
  { id: 'v1', name: 'Arabian Vista Villa', area: 'Jumeirah Beach', city: 'Dubai', state: 'UAE', type: 'villa', guests: 8, bedrooms: 4, bathrooms: 4, price: 40000, rating: 4.8, coords: {lat: 25.2048, lng: 55.2708}, address: 'Arabian Vista Villa, Jumeirah Beach, Dubai', video: 'https://cdn.coverr.co/videos/coverr-sun-light-on-pool-4360/1080p.mp4', image: 'Images/villaA.jpg', gallery: ['Images/villaA.jpg','Images/villaB.jpg','Images/villaC.jpg','Images/villaD.jpg'], tags: ['seaview','private-pool','luxury'], amenities: ['Private pool','Sea view deck','Chef on request','Wi‑Fi','Air conditioning','Power backup'], owner: { name: 'Abel', phone: '+91 9372560325', email: 'priya@trip2trip.example' }, reviews: [{user: 'Alice Johnson', rating: 5, comment: 'Amazing villa with stunning views!', date: '2023-10-01'}, {user: 'Bob Smith', rating: 4, comment: 'Great experience, highly recommend.', date: '2023-09-15'}] },
  { id: 'r1', name: 'Bayfront Royale Resort', area: 'Panchgani', city: 'Satara', state: 'Maharashtra', type: 'resort', guests: 4, bedrooms: 1, bathrooms: 1, price: 5000, rating: 4.6, coords: {lat: 17.9237, lng: 73.7987}, address: 'Bayfront Royale Resort, Panchgani, Satara', video: 'https://cdn.coverr.co/videos/coverr-pool-side-view-9170/1080p.mp4', image: 'Images/bayA.jpg', gallery: ['Images/bayA.jpg','Images/bayB.jpg','Images/bayC.jpg'], tags: ['family','seaview'], amenities: ['Beach access','Spa','Gym','Breakfast included','Wi‑Fi'], owner: { name: 'Rahul Verma', phone: '+91 90000 22222', email: 'rahul@trip2trip.example' }, reviews: [] },
  { id: 'v2', name: 'Palm Grove Estate', area: 'Alibaug', city: 'Raigad', state: 'Maharashtra', type: 'villa', guests: 12, bedrooms: 5, bathrooms: 5, price: 27000, rating: 4.9, coords: {lat: 18.6414, lng: 72.8722}, address: 'Palm Grove Estate, Alibaug, Raigad', video: 'https://cdn.coverr.co/videos/coverr-blissful-sea-waves-4038/1080p.mp4', image: 'Images/Palm1.jpg', gallery: ['Images/Palm1.jpg','Images/Palm2.jpg','Images/Palm3.jpg','Images/Palm4.jpg'], tags: ['private-pool','family','luxury'], amenities: ['Private lawn','Pool','BBQ','Wi‑Fi','Air conditioning'], owner: { name: 'Aisha Khan', phone: '+91 90000 33333', email: 'aisha@trip2trip.example' }, reviews: [{user: 'Charlie Brown', rating: 5, comment: 'Perfect for family gatherings.', date: '2023-11-05'}] },
  { id: 'r2', name: 'Conrad Marine Bay', area: 'Bandra', city: 'Mumbai', state: 'Maharashtra', type: 'resort', guests: 2, bedrooms: 1, bathrooms: 1, price: 12000, rating: 4.4, coords: {lat: 19.0596, lng: 72.8295}, address: 'Conrad Marine Bay, Bandra West, Mumbai', video: 'https://cdn.coverr.co/videos/coverr-night-pool-8070/1080p.mp4', image: 'Images/marina1.jpg', gallery: ['Images/marina1.jpg','Images/marina2.jpg','Images/marina3.jpg'], tags: ['pet','family'], amenities: ['City view','Restaurant','Wi‑Fi'], owner: { name: 'Neeraj Patel', phone: '+91 90000 44444', email: 'neeraj@trip2trip.example' }, reviews: [] },
  { id: 'v3', name: 'Sea Cliff Mansion', area: 'Malabar Hill', city: 'Mumbai', state: 'Maharashtra', type: 'villa', guests: 6, bedrooms: 3, bathrooms: 3, price: 38000, rating: 4.7, coords: {lat: 18.9548, lng: 72.7928}, address: 'Sea Cliff Mansion, Ridge Road, Malabar Hill, Mumbai', video: 'https://cdn.coverr.co/videos/coverr-seaside-sunrise-7893/1080p.mp4', image: 'Images/sea1.jpg', gallery: ['Images/sea1.jpg','Images/sea2.jpg','Images/sea3.jpg'], tags: ['seaview','luxury'], amenities: ['Infinity pool','Terrace','Wi‑Fi','Chef on request'], owner: { name: 'Rhea Dsouza', phone: '+91 90000 55555', email: 'rhea@trip2trip.example' }, reviews: [] },
  { id: 'r3', name: 'Lotus Cove Retreat', area: 'Versova', city: 'Mumbai', state: 'Maharashtra', type: 'resort', guests: 3, bedrooms: 1, bathrooms: 1, price: 9000, rating: 4.3, coords: {lat: 19.1334, lng: 72.8234}, address: 'Lotus Cove Retreat, Versova Beach Road, Mumbai', video: 'https://cdn.coverr.co/videos/coverr-palms-and-pool-1530/1080p.mp4', image: 'Images/cove1.jpg', gallery: ['Images/cove1.jpg','Images/cove2.jpg'], tags: ['family'], amenities: ['Breakfast','Gym','Wi‑Fi'], owner: { name: 'Karan Mehta', phone: '+91 90000 66666', email: 'karan@trip2trip.example' }, reviews: [] }
];

